# Generated by Django 3.1.7 on 2021-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_animemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamennModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('postdate', models.DateField(auto_now_add=True)),
                ('content', models.CharField(max_length=400)),
                ('picture', models.SlugField()),
            ],
        ),
    ]
