# Generated by Django 3.1.7 on 2021-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_ramennmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animemodel',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='infomation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
