# Generated by Django 3.1.7 on 2021-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0009_auto_20210323_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='hp',
            field=models.TextField(default='https://www.tus.ac.jp/'),
        ),
    ]
