# Generated by Django 3.1.7 on 2021-03-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0012_auto_20210323_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
