# Generated by Django 3.1.7 on 2021-03-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0013_animemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramennmodel',
            name='picture',
            field=models.FileField(upload_to='static/img/Ramenn/'),
        ),
    ]
