# Generated by Django 3.1.7 on 2021-03-24 04:03

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0014_auto_20210324_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
